//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RAL_DAL
{
    using System;
    using System.Collections.Generic;
    
    [Table("Users")]
    public partial class User
    {
        public User()
        {
            this.plans = new HashSet<Plan>();
            this.watcheda = new HashSet<Watcheda>();
        }
    
        [Key]
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string regtime { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Plan> plans { get; set; }
        public virtual ICollection<Watcheda> watcheda { get; set; }
    }
}
